# Generated by Django 6.0.6 on 2026-07-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='prep_time_minutes',
            field=models.IntegerField(default=15),
        ),
    ]
