# Generated by Django 6.0.6 on 2026-07-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_ready_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
